name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build sites, move to build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Clean install dependencies, build todoapp
        run: |
          npm ci
          cd packages/react-openapi-client-generator/examples/todoapp
          npm run build
          mkdir -p ../../../../public/react-openapi-client-generator/examples/todoapp
          mv build/* $_

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
